service: dev-xana-media-processing
frameworkVersion: "3"

provider:
  name: aws
  stackName: xana-media-handler
  stage: dev
  region: us-east-1


  iam:
    role: arn:aws:iam::845847047647:role/mohneesh-transcoder-role-for-lambda

  environment:
    #    variable1: value1
    ACCESS_KEY_ID: AKIA4J4DJVXPY3ZJFXNS
    ACCESS_SECRET: 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
# you can add packaging information here
package:
  #  individually: true
  excludeDevDependencies: true
  patterns:
    - "handler.js"
    - "!node_modules/**"
    - "!*.json"
  #    - '!exclude-me-dir/**'
  #    - include-me.js
  #    - include-me-dir/**

functions:
  dev-xana-compress-image:
    name: dev-xana-image-compression
    runtime: nodejs14.x
    memorySize: 2048
    description: This lambda cretes compressed images for serving in XANA application
    handler: handler.main
    events:
      - sqs:
          arn: arn:aws:sqs:us-east-1:845847047647:dev-xana-resizeImages
    timeout: 20
    layers:
      - { Ref: CommonLibs14LambdaLayer }
    environment:
      ACCESSKEYID: AKIA4J4DJVXPY3ZJFXNS
      SECRETACCESSKEY: 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
    package:
      individually: true

layers:
  commonLibs14:
    path: layer
    compatibleRuntimes:
      - nodejs14.x
